      # - pattern: java.lang<type=(.+), name=(.+)><(.+)>(\w+)
      #   name: jvm_$1_$4_$3_$2
      # - pattern: java.lang<type=(.+), name=(.+)><>(\w+)
      #   name: jvm_$1_$3_$2
      # - pattern : java.lang<type=(.*)>

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-jmx-custom
data:
  jmx-kafka-prometheus.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:5555/jmxrmi
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    ssl: false
    # whitelistObjectNames: ["kafka.controller:*","kafka.server:*","java.lang:*","kafka.network:*","kafka.log:*"]
    rules:
      - pattern: ".*"