# kubectl apply -f values/sasl-secret-sample.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sasl-secret-sample
type: Opaque

# Secret 매니페스트에선 보안을 위해 base64로 인코딩된 값을 할당해야하지만, data대신 stringData를 쓰면 쿠버네티스가 알아서 변환함
# Production Ready에선 파일관리 주의
stringData:  
  client-passwords: "00000,11111,22222"
  inter-broker-password: "1234"
  controller-password: "1234"
  # inter-broker-client-secret: "INTER_BROKER_CLIENT_SECRET"
  # controller-client-secret: "CONTROLLER_CLIENT_SECRET"
  # zookeeper-password: "ZOOKEEPER_PASSWORD"




# 일회성 생성은 다음과 같이
# kubectl create secret generic SECRET_NAME \
#   --from-literal=client-passwords=CLIENT_PASSWORD1,CLIENT_PASSWORD2 \
#   --from-literal=inter-broker-password=INTER_BROKER_PASSWORD \
#   --from-literal=inter-broker-client-secret=INTER_BROKER_CLIENT_SECRET \
#   --from-literal=controller-password=CONTROLLER_PASSWORD \
#   --from-literal=controller-client-secret=CONTROLLER_CLIENT_SECRET \
#   --from-literal=zookeeper-password=ZOOKEEPER_PASSWORD