apiVersion: v2
name: skafka
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "3.5.1"  # kafka version 기준



dependencies:
  - name: kafka
    version: 25.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  # 서브차트 kafka의 서브차트 common을 직접 사용시 각 서브차트간 커플링이 심해진다.
  # 따라서 최상위 차트의 서브차트로 common을 추가해준다.
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common

  - name: kafka-connect
    version: 0.2.1
    repository: https://licenseware.github.io/charts/
    alias: connect
    condition: connect.enabled
  
  - name: kubernetes-dashboard
    version: 6.0.7
    repository: https://kubernetes.github.io/dashboard/
    alias: k8dashboard
    condition: k8dashboard.enabled
    
  - name: kafka-ui
    version: 0.7.6
    repository: https://provectus.github.io/kafka-ui-charts
    alias: ui4kafka
    condition: ui4kafka.enabled
